# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  global:
    PYTHONIOENCODING: utf-8
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

## Before repo cloning
init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -V

## After repo cloning
install:

build: false

## Before tests
before_test:
  - pip install minimock nose pystache mako  ## should use ``python setup.py``

## Custom test script
test_script:

  ## Fail early on big problems
  - "python src\\gitchangelog\\gitchangelog.py --debug"
  - "python src\\gitchangelog\\gitchangelog.py --debug e98a0fe8^^..e98a0fe8"

  ## real tests
  - nosetests -sx .