# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"

init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - set PYTHONIOENCODING=utf-8
  - python -V

build: false

test_script:
  - "python src\\gitchangelog\\gitchangelog.py --debug"
  - "python src\\gitchangelog\\gitchangelog.py --debug show e98a0fe8^^..e98a0fe8"

